import type { Metadata } from "next";
import { Bree_Serif, Literata } from "next/font/google";
import "./globals.css";

import { Heading1 } from "@/components/headings";
import MainNav from "@/components/main-nav";
import { ProfileDropdown } from "@/components/ProfileDropdown";

const breeSerif = Bree_Serif({
  weight: ["400"],
  style: "normal",
  subsets: ["latin"],
});
const literata = Literata({
  weight: ["400", "600", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${literata.className} bg-background`}>
        <header
          className={` flex flex-col items-center justify-center p-4  bg-green-600 text-primary-foreground`}
        >
          <Heading1 content="Pet Tracker" />

          <MainNav />
        </header>
        <main className="flex flex-col items-center">{children}</main>
      </body>
    </html>
  );
}
